<?php
/**
 * @category   Inventionstar
 * @package    Inventionstar_DeleteOrders
 * @author     guptapankaj775@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Inventionstar\DeleteOrders\Model\Config\Source;

use Magento\Framework\Option\ArrayInterface;

/**
 * Class Country
 *
 * @package Inventionstar\DeleteOrders\Model\Config\Source
 */
class Country implements ArrayInterface
{
    const SPECIFIC = '1';
    const ALL      = '2';

    /**
     * Return array of options as value-label pairs
     *
     * @return array Format: array(array('value' => '<value>', 'label' => '<label>'), ...)
     */
    public function toOptionArray()
    {
        return [
            ['value' => self::ALL, 'label' => __('All Countries')],
            ['value' => self::SPECIFIC, 'label' => __('Specific Countries')]
        ];
    }
}
