<?php
/**
 * @category   Inventionstar
 * @package    Inventionstar_DeleteOrders
 * @author     guptapankaj775@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
namespace Inventionstar\DeleteOrders\Model\Config\Source;

/**
 * Class Frequency
 *
 * @package Inventionstar\DeleteOrders\Model\Config\Source
 */
class Frequency extends \Magento\Cron\Model\Config\Source\Frequency
{
    const DISABLE = 0;

    /**
     * @return array
     */
    public function toOptionArray()
    {
        parent::toOptionArray();

        array_unshift(self::$_options, ['label' => __('Disable'), 'value' => self::DISABLE]);

        return self::$_options;
    }
}
